#pragma once

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES
// #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_RAINDROPS
// #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_GRADIENT_UP_DOWN
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CUSTOM_lol
#define RGBLIGHT_LAYERS

#undef DEBOUNCE
#define DEBOUNCE 10
